export default function Sponsor() {

  return (
    <div className="allm-mt-4 allm-pl-4 allm-text-xs allm-w-11/12 allm-font-sans allm-t ext-slate-500 allm-pr-36 allm-text-wrap">
      <p>
        Want to speak with one of our consultants? <a
          href="https://www.emigreat.io/contact"
          target="_blank"
          rel="noreferrer"
          className="hover:allm-opacity-80 hover:allm-underline allm-text-slate-700"
        >Contact us</a> and we'll get back to you within 2 business days.
      </p>
      <p>
        Emigreat provides this AI bot for general informational purposes only. No attorney-client relationship is formed by using this bot. Emigreat is not responsible for any errors or inaccuracies in the replies generated by this bot. Always consult a qualified legal professional for any legal issues.
      </p>
      <p>
        This bot utilizes <a href="https://useanything.com/" className="hover:allm-opacity-80 hover:allm-underline allm-text-slate-700">AnythingLLM</a> which is open-source under the <a href="https://docs.useanything.com/licence.txt" className="hover:allm-opacity-80 hover:allm-underline allm-text-slate-700">MIT License</a>.
      </p>
    </div>
  );
}
